'use client';
import {useEffect,useRef,useState} from 'react';
import maplibregl from 'maplibre-gl';
import 'maplibre-gl/dist/maplibre-gl.css';
import {api} from '../lib/api';

const colors:any={SAFE:'#2e7d32',LOW:'#2e7d32',MODERATE:'#eab308',HIGH:'#d97706',CRITICAL:'#b42318'};
export default function MapDemo(){
 const ref=useRef<HTMLDivElement>(null); const map=useRef<maplibregl.Map|null>(null); const [zones,setZones]=useState<any[]>([]); const [selected,setSelected]=useState<any>();
 useEffect(()=>{api('/api/v1/zones').then(setZones).catch(()=>{})},[]);
 useEffect(()=>{if(!ref.current)return; map.current=new maplibregl.Map({container:ref.current,style:{version:8,sources:{},layers:[{id:'bg',type:'background',paint:{'background-color':'#e6edf3'}}]},center:[91.73,25.27],zoom:6}); map.current.addControl(new maplibregl.NavigationControl(),'top-right'); return()=>{map.current?.remove();map.current=null}},[]);
 useEffect(()=>{const m=map.current;if(!m||!zones.length)return;const add=()=>{if(m.getSource('zones'))m.removeSource('zones');for(const l of Object.keys(colors)){if(m.getLayer(`zone-${l}`))m.removeLayer(`zone-${l}`)}m.addSource('zones',{type:'geojson',data:{type:'FeatureCollection',features:zones.map(z=>({type:'Feature',properties:{id:z.id,level:z.risk_level},geometry:{type:'Point',coordinates:[z.lon,z.lat]}}))}} as any);Object.keys(colors).forEach(level=>{m.addLayer({id:`zone-${level}`,type:'circle',source:'zones',filter:['==',['get','level'],level],paint:{'circle-radius':9,'circle-color':colors[level],'circle-stroke-color':'#fff','circle-stroke-width':2}});});m.on('click','zone-CRITICAL',click);m.on('click','zone-HIGH',click);m.on('click','zone-MODERATE',click);m.on('click','zone-LOW',click);m.on('click','zone-SAFE',click)};const click=(e:any)=>{const f=e.features?.[0];const z=zones.find(x=>x.id===f?.properties?.id);if(z)setSelected(z)};if(m.isStyleLoaded())add();else m.once('load',add);return()=>{['CRITICAL','HIGH','MODERATE','LOW','SAFE'].forEach(l=>{try{m.off('click',`zone-${l}`,click)}catch{}})}},[zones]);
 return <div className="map"><div ref={ref} style={{position:'absolute',inset:0}}/><div style={{position:'absolute',top:12,left:12,zIndex:2,background:'#fff',border:'1px solid #ccd5df',padding:10,fontSize:12}}><b>NER RISK MAP</b><div className="muted">Synthetic / Demo Data · GIS layers</div></div>{selected&&<div className="card" style={{position:'absolute',right:12,top:12,zIndex:3,width:300}}><b>{selected.name}</b><div className="muted">{selected.district}, {selected.state}</div><div className="risk-number" style={{fontSize:38}}>{selected.risk_score}</div><span className={`badge badge-${selected.risk_level.toLowerCase()}`}>{selected.risk_level}</span><p className="muted">Confidence {Math.round(selected.confidence*100)}% · {selected.trend}</p><p>Population exposure: <b>{selected.population_exposure.toLocaleString()}</b></p><p>Factors: {(selected.factors||[]).map((f:any)=>f.name).join(', ')||'Rainfall, soil moisture, slope'}</p><button className="btn" onClick={()=>setSelected(undefined)}>Close</button></div>}<div style={{position:'absolute',bottom:12,left:12,zIndex:2,background:'#fff',padding:8,border:'1px solid #ccd5df',fontSize:11}}>SAFE · LOW · MODERATE · HIGH · CRITICAL</div></div>
}
