'use client';
import Link from 'next/link';import {useEffect,useState} from 'react';import {usePathname,useRouter} from 'next/navigation';import OfflineBanner from './OfflineBanner';import {login,saveSession,getUser,clearSession} from '../lib/api';
export default function MobileShell({children,title='PATKAI Safety'}:{children:React.ReactNode,title?:string}){
 const [ready,setReady]=useState(false),[online,setOnline]=useState(true),[user,setUser]=useState<any|null>(null),[email,setEmail]=useState('citizen@patkai.demo'),[password,setPassword]=useState('Patkai@2026'),[error,setError]=useState('');const router=useRouter();const pathname=usePathname();
 useEffect(()=>{setOnline(navigator.onLine);const on=()=>setOnline(navigator.onLine);addEventListener('online',on);addEventListener('offline',on);return()=>{removeEventListener('online',on);removeEventListener('offline',on)}},[]);
 useEffect(()=>{setUser(getUser('citizen'));setReady(true)},[]);
 const signIn=async()=>{setError('');try{const x=await login(email,password);if(x.user.role!=='CITIZEN'){throw new Error('Use a citizen account for the citizen app.')}saveSession('citizen',x);setUser(x.user)}catch(e:any){setError(e.message||'Unable to sign in')}};
 const logout=()=>{clearSession('citizen');setUser(null)};
 const nav=[['/app','Home'],['/app/map','Map'],['/app/alerts','Alerts'],['/app/report','Report'],['/app/settings','Profile']];
 return <div className="safety"><OfflineBanner/><header className="citizen-header"><button className="menu-btn" aria-label="Open menu">☰</button><div className="citizen-brand"><b>Landsafe NER</b></div><div className="citizen-user">{user?<><span className="online-dot"/> <span>{user.email.split('@')[0]}</span></>:<span>Citizen</span>}</div></header>{user&&<div className="citizen-account"><div><b>{user.email}</b><span>{user.role}{user.district?` · ${user.district}`:''}</span></div><button onClick={logout}>Log out</button></div>}<div className="citizen-title-row"><h1>{title}</h1><span className="status-pill">{online?'ONLINE':'OFFLINE'}</span></div>{ready&&user?children:<div className="card citizen-login"><div className="brand">Landsafe NER</div><h2>Citizen sign in</h2><p className="muted">Access local risk, maps, alerts and hazard reporting.</p><label>Email</label><input className="input" value={email} onChange={e=>setEmail(e.target.value)}/><label>Password</label><input className="input" type="password" value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<div className="notice">{error}</div>}<button className="btn btn-primary full-btn" onClick={signIn}>Sign in as citizen</button><p className="footer-note">Demo citizen: citizen@patkai.demo · Patkai@2026</p><Link className="switch-link" href="/gov/login">Government / officer login →</Link></div>}<nav className="citizen-nav">{nav.map(([href,label])=><Link className={pathname===href?'active':''} key={href} href={href}><span>{label==='Home'?'⌂':label==='Map'?'⌖':label==='Alerts'?'♢':label==='Report'?'!':'♙'}</span><b>{label}</b></Link>)}</nav></div>
}
