'use client';
import {useState} from 'react';import exifr from 'exifr';import MobileShell from '../../../components/MobileShell';import {api,API,getToken} from '../../../lib/api';import {queueReport} from '../../../lib/offline';

type Check={label:string,status:'good'|'warn'|'bad',detail:string};
export default function Page(){
 const[type,setType]=useState('Landslide'),[desc,setDesc]=useState(''),[sev,setSev]=useState('MODERATE'),[msg,setMsg]=useState(''),[file,setFile]=useState<File|null>(null),[checks,setChecks]=useState<Check[]>([]),[busy,setBusy]=useState(false);
 async function inspect(f:File){
   const c:Check[]=[]; c.push({label:'File type',status:f.type.startsWith('image/')?'good':'bad',detail:f.type||'Unknown'});c.push({label:'File size',status:f.size<=8*1024*1024?'good':'bad',detail:`${(f.size/1024/1024).toFixed(2)} MB · limit 8 MB`});
   try{const ex=await exifr.parse(f,{gps:true,tiff:true,exif:true});const gps=ex?.latitude!=null&&ex?.longitude!=null;const dt=ex?.DateTimeOriginal||ex?.DateTimeDigitized||ex?.DateTime;const device=!!(ex?.Make||ex?.Model);c.push({label:'GPS metadata',status:gps?'good':'warn',detail:gps?`${Number(ex.latitude).toFixed(5)}, ${Number(ex.longitude).toFixed(5)}`:'Not present — report will need verification'});c.push({label:'Capture timestamp',status:dt?'good':'warn',detail:dt?String(dt):'Not present'});c.push({label:'Device metadata',status:device?'good':'warn',detail:device?`${ex.Make||''} ${ex.Model||''}`.trim():'Not present'});}catch{c.push({label:'EXIF metadata',status:'warn',detail:'Could not be read in browser; server-side verification will run after upload'});}
   setChecks(c);
 }
 async function submit(){
   setBusy(true);setMsg('');let lat:number|undefined,lon:number|undefined;try{const p=await new Promise<GeolocationPosition>((res,rej)=>navigator.geolocation.getCurrentPosition(res,rej,{enableHighAccuracy:true,timeout:8000}));lat=p.coords.latitude;lon=p.coords.longitude}catch{}
   const key=crypto.randomUUID();const capturedAt=new Date().toISOString();
   try{
    if(navigator.onLine){
      if(file){const fd=new FormData();fd.append('incident_type',type);fd.append('description',desc);fd.append('severity',sev);if(lat!==undefined)fd.append('lat',String(lat));if(lon!==undefined)fd.append('lon',String(lon));fd.append('idempotency_key',key);fd.append('file',file);const x=await fetch(`${API}/api/v1/reports/upload`,{method:'POST',headers:{Authorization:`Bearer ${getToken('citizen')}`},body:fd});const j=await x.json();if(!x.ok)throw new Error(j.detail||'Upload failed');setMsg(`Report accepted · Trust ${j.trust_score}/100 · ${j.verification_status}. Government verification remains the final decision.`)}
      else {const x=await api('/api/v1/reports',{method:'POST',body:JSON.stringify({incident_type:type,description:desc,severity:sev,lat,lon,captured_at:capturedAt,idempotency_key:key,metadata:{client_timestamp:capturedAt}})});setMsg(`Report accepted · ID ${String(x.id||'').slice(0,8)}`)}
    }else{await queueReport({incident_type:type,description:desc,severity:sev,lat,lon,captured_at:capturedAt,idempotency_key:key,metadata:{queued_offline:true},fileBlob:file});setMsg('OFFLINE: report saved on this phone and will sync when the connection returns.')}
   }catch(e:any){setMsg(e.message||'Unable to submit report. Please try again.')}finally{setBusy(false)}
 }
 return <MobileShell title="Report a Hazard"><div className="card report-card"><div className="section-label">1 · What did you observe?</div><label>Report type</label><select className="input" value={type} onChange={e=>setType(e.target.value)}>{['Landslide','Crack','Slope movement','Road blockage','Rockfall','Flooding','Infrastructure damage','Other'].map(x=><option key={x}>{x}</option>)}</select><label>Severity</label><select className="input" value={sev} onChange={e=>setSev(e.target.value)}><option>LOW</option><option>MODERATE</option><option>HIGH</option><option>CRITICAL</option></select><label>Description</label><textarea className="input" rows={5} value={desc} onChange={e=>setDesc(e.target.value)} placeholder="What happened? What is blocked or damaged?"/><div className="section-label">2 · Add evidence</div><label className="upload-box"><span className="upload-icon">＋</span><b>{file?file.name:'Take or choose a photo'}</b><small>Images are checked for metadata, duplicates and consistency.</small><input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={e=>{const f=e.target.files?.[0]||null;setFile(f);if(f)inspect(f)}}/></label>{checks.length>0&&<div className="verification-card"><b>Pre-upload evidence check</b>{checks.map((c,i)=><div className="check-row" key={i}><span className={`check-dot ${c.status}`}>{c.status==='good'?'✓':c.status==='bad'?'!':'i'}</span><div><b>{c.label}</b><div className="muted">{c.detail}</div></div></div>)}<div className="footer-note">Metadata is a trust signal, not proof that an image is genuine or fake. Final verification is performed by authorized officers.</div></div>}<div className="location-strip"><b>Location</b><span>GPS will be captured when permission is available</span></div><button disabled={busy||!file&&desc.trim().length<5} className="btn btn-danger full-btn" onClick={submit}>{busy?'Checking & submitting…':'Submit hazard report'}</button>{msg&&<div className="notice" style={{marginTop:12}}>{msg}</div>}</div></MobileShell>}
